import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:intl/intl.dart';
import 'models/domain.dart';
import 'services/app_state.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try { await dotenv.load(fileName: '.env'); } catch (_) {}
  final state = AppState();
  await state.initialize();
  runApp(QuickServeApp(state: state));
}

class QuickServeApp extends StatelessWidget {
  const QuickServeApp({super.key, required this.state});
  final AppState state;
  @override Widget build(BuildContext context) => AnimatedBuilder(animation: state, builder: (_, __) => MaterialApp(debugShowCheckedModeBanner: false, title: 'QuickServe', theme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFF26B4D), brightness: Brightness.light), scaffoldBackgroundColor: const Color(0xFFFBFAF8), inputDecorationTheme: const InputDecorationTheme(border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(14)), borderSide: BorderSide.none), filled: true, fillColor: Colors.white)), home: state.authenticated ? HomeShell(state: state) : AuthScreen(state: state)));
}

class AuthScreen extends StatefulWidget { const AuthScreen({super.key, required this.state}); final AppState state; @override State<AuthScreen> createState() => _AuthScreenState(); }
class _AuthScreenState extends State<AuthScreen> {
  bool register = false; final email = TextEditingController(text: 'aditi.sharma@email.com'); final password = TextEditingController(text: 'password'); final name = TextEditingController(text: 'Aditi Sharma');
  @override Widget build(BuildContext context) => Scaffold(body: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 460), child: Padding(padding: const EdgeInsets.all(28), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [CircleAvatar(radius: 30, backgroundColor: const Color(0xFFF26B4D), child: const Icon(Icons.home_repair_service, color: Colors.white)), const SizedBox(height: 12), const Text('quickserve', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800, color: Color(0xFFF26B4D))), const SizedBox(height: 32), Text(register ? 'Create your account.' : 'Welcome back.', style: const TextStyle(fontSize: 30, fontWeight: FontWeight.w800)), const SizedBox(height: 8), Text(register ? 'Get trusted help for every room.' : 'Sign in to keep your home running smoothly.', style: TextStyle(color: Colors.grey.shade600)), const SizedBox(height: 26), if (register) TextField(controller: name, decoration: const InputDecoration(labelText: 'Full name')), if (register) const SizedBox(height: 12), TextField(controller: email, decoration: const InputDecoration(labelText: 'Email address')), const SizedBox(height: 12), TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'Password')), const SizedBox(height: 16), SizedBox(width: double.infinity, child: FilledButton(onPressed: widget.state.loading ? null : () async { if (register) { await widget.state.register(name.text, email.text, password.text); } else { final requestedRole = email.text.toLowerCase().contains('admin') ? AppRole.admin : email.text.toLowerCase().contains('agent') ? AppRole.agent : AppRole.customer; await widget.state.signIn(email.text, password.text, requestedRole); } if (mounted && widget.state.errorMessage != null) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(widget.state.errorMessage!))); setState(() {}); }, child: Text(register ? 'Create account' : 'Sign in'))), TextButton(onPressed: () => setState(() => register = !register), child: Text(register ? 'Already have an account? Sign in' : 'New to QuickServe? Create an account')), TextButton(onPressed: () async { await widget.state.resetPassword(email.text); if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('If the email exists, a reset link has been sent.'))); }, child: const Text('Forgot password?'))]))));
}

class HomeShell extends StatefulWidget { const HomeShell({super.key, required this.state}); final AppState state; @override State<HomeShell> createState() => _HomeShellState(); }
class _HomeShellState extends State<HomeShell> { int index = 0; @override Widget build(BuildContext context) { final pages = [HomeScreen(state: widget.state), RequestsScreen(state: widget.state), ProfileScreen(state: widget.state)]; return Scaffold(body: pages[index], bottomNavigationBar: NavigationBar(selectedIndex: index, onDestinationSelected: (i) => setState(() => index = i), destinations: const [NavigationBarDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home), label: 'Home'), NavigationBarDestination(icon: Icon(Icons.assignment_outlined), selectedIcon: Icon(Icons.assignment), label: 'Requests'), NavigationBarDestination(icon: Icon(Icons.person_outline), selectedIcon: Icon(Icons.person), label: 'Profile')])); } }

class HomeScreen extends StatelessWidget { const HomeScreen({super.key, required this.state}); final AppState state; @override Widget build(BuildContext context) { final activeItems = state.visibleRequests.where((r) => r.status != RequestStatus.completed && r.status != RequestStatus.cancelled).toList(); final active = activeItems.isEmpty ? null : activeItems.first; return AppPage(title: 'Good morning, ${state.actorName}', eyebrow: DateFormat('EEEE, d MMMM').format(DateTime.now()), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [HeroCard(onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => CreateRequestScreen(state: state)))), const SizedBox(height: 18), if (active != null) RequestCard(request: active, onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => RequestDetailScreen(state: state, request: active)))), const SizedBox(height: 22), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('What do you need help with?', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800)), TextButton(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => ServicesScreen(state: state))), child: const Text('See all'))]), Wrap(spacing: 10, runSpacing: 10, children: ServiceType.values.map((s) => ServiceTile(service: s, onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => CreateRequestScreen(state: state, initialService: s))))).toList()), const SizedBox(height: 24), Card(color: const Color(0xFFE4F7F2), child: const ListTile(leading: Icon(Icons.verified_user, color: Color(0xFF1E9E96)), title: Text('Trusted professionals, every time', style: TextStyle(fontWeight: FontWeight.w700)), subtitle: Text('Every agent is background-verified and rated by customers.')))])); } }

class ServicesScreen extends StatelessWidget { const ServicesScreen({super.key, required this.state}); final AppState state; @override Widget build(BuildContext context) => AppPage(title: 'Services', eyebrow: 'HOME SERVICES, MADE EASY', child: Wrap(spacing: 12, runSpacing: 12, children: ServiceType.values.map((s) => SizedBox(width: 180, child: ServiceTile(service: s, large: true, onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => CreateRequestScreen(state: state, initialService: s))))).toList())); }

class CreateRequestScreen extends StatefulWidget { const CreateRequestScreen({super.key, required this.state, this.initialService}); final AppState state; final ServiceType? initialService; @override State<CreateRequestScreen> createState() => _CreateRequestScreenState(); }
class _CreateRequestScreenState extends State<CreateRequestScreen> { late ServiceType service = widget.initialService ?? ServiceType.ac; Priority priority = Priority.medium; DateTime date = DateTime.now(); final description = TextEditingController(); final time = TextEditingController(text: '4:00 PM – 6:00 PM'); final address = TextEditingController(text: 'Flat 402, Lotus Heights, Pratap Nagar'); @override Widget build(BuildContext context) => AppPage(title: 'Create request', eyebrow: 'NEW SERVICE REQUEST', child: ListView(shrinkWrap: true, children: [DropdownButtonFormField(value: service, decoration: const InputDecoration(labelText: 'Service type'), items: ServiceType.values.map((s) => DropdownMenuItem(value: s, child: Text(s.label))).toList(), onChanged: (v) => setState(() => service = v!)), const SizedBox(height: 12), TextField(controller: description, maxLines: 4, decoration: const InputDecoration(labelText: 'Describe the issue')), const SizedBox(height: 12), TextField(controller: address, decoration: const InputDecoration(labelText: 'Address')), const SizedBox(height: 12), Row(children: [Expanded(child: ListTile(contentPadding: EdgeInsets.zero, title: Text(DateFormat('d MMM yyyy').format(date)), subtitle: const Text('Preferred date'), trailing: const Icon(Icons.calendar_today), onTap: () async { final picked = await showDatePicker(context: context, firstDate: DateTime.now(), lastDate: DateTime.now().add(const Duration(days: 90)), initialDate: date); if (picked != null) setState(() => date = picked); })), const SizedBox(width: 8), Expanded(child: TextField(controller: time, decoration: const InputDecoration(labelText: 'Time')))]), const SizedBox(height: 12), DropdownButtonFormField(value: priority, decoration: const InputDecoration(labelText: 'Priority'), items: Priority.values.map((p) => DropdownMenuItem(value: p, child: Text(p.label))).toList(), onChanged: (v) => setState(() => priority = v!)), const SizedBox(height: 20), FilledButton.icon(onPressed: () async { final request = await widget.state.createRequest(service: service, description: description.text, date: date, time: time.text, address: address.text, priority: priority); if (context.mounted && request != null) { Navigator.pop(context); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('${request.id} created successfully'))); } }, icon: const Icon(Icons.send), label: const Text('Submit request'))])); }

class RequestsScreen extends StatefulWidget { const RequestsScreen({super.key, required this.state}); final AppState state; @override State<RequestsScreen> createState() => _RequestsScreenState(); }
class _RequestsScreenState extends State<RequestsScreen> { String search = ''; ServiceType? filter; @override Widget build(BuildContext context) { final requests = widget.state.visibleRequests.where((r) => (filter == null || r.service == filter) && ('${r.id} ${r.description} ${r.address}'.toLowerCase().contains(search.toLowerCase()))).toList(); return AppPage(title: 'My requests', eyebrow: 'YOUR SERVICE HISTORY', child: Column(children: [TextField(decoration: const InputDecoration(prefixIcon: Icon(Icons.search), hintText: 'Search requests, addresses, agents…'), onChanged: (v) => setState(() => search = v)), const SizedBox(height: 10), SingleChildScrollView(scrollDirection: Axis.horizontal, child: Row(children: [FilterChip(label: const Text('All'), selected: filter == null, onSelected: (_) => setState(() => filter = null)), ...ServiceType.values.map((s) => Padding(padding: const EdgeInsets.only(left: 8), child: FilterChip(label: Text(s.label), selected: filter == s, onSelected: (_) => setState(() => filter = s))))])), const SizedBox(height: 12), ...requests.map((r) => Padding(padding: const EdgeInsets.only(bottom: 10), child: RequestCard(request: r, onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => RequestDetailScreen(state: widget.state, request: r))))))])); } }

class RequestDetailScreen extends StatelessWidget { const RequestDetailScreen({super.key, required this.state, required this.request}); final AppState state; final ServiceRequest request; @override Widget build(BuildContext context) => AppPage(title: request.id, eyebrow: request.service.label.toUpperCase(), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Card(child: ListTile(title: Text(request.description), subtitle: Text('${request.address}\n${DateFormat('d MMM yyyy').format(request.preferredDate)} · ${request.preferredTime}'))), const SizedBox(height: 18), Text('Request progress', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 12), ...lifecycle.map((status) => ListTile(leading: CircleAvatar(backgroundColor: lifecycle.indexOf(status) <= lifecycle.indexOf(request.status) ? const Color(0xFF1E9E96) : Colors.grey.shade200, child: Icon(lifecycle.indexOf(status) <= lifecycle.indexOf(request.status) ? Icons.check : Icons.circle, color: Colors.white, size: 16)), title: Text(status.label), dense: true)), if (request.assignedAgent != null) ListTile(leading: const Icon(Icons.person), title: Text(request.assignedAgent!), subtitle: Text(request.agentNote ?? 'Assigned service professional')), if (request.status == RequestStatus.created || request.status == RequestStatus.assigned) OutlinedButton.icon(onPressed: () async { await state.updateStatus(request, RequestStatus.cancelled); if (context.mounted) Navigator.pop(context); }, icon: const Icon(Icons.close), label: const Text('Cancel request'))])); }

class ProfileScreen extends StatelessWidget { const ProfileScreen({super.key, required this.state}); final AppState state; @override Widget build(BuildContext context) => AppPage(title: 'Profile', eyebrow: 'ACCOUNT', child: Column(children: [CircleAvatar(radius: 36, child: Text(state.actorName.isEmpty ? 'Q' : state.actorName[0])), const SizedBox(height: 10), Text(state.actorName, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w800)), Text(state.role.label, style: TextStyle(color: Colors.grey.shade600)), const SizedBox(height: 24), if (state.role == AppRole.admin) ListTile(leading: const Icon(Icons.dashboard), title: const Text('Operations console'), trailing: const Icon(Icons.chevron_right), onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => AdminScreen(state: state)))), if (state.role == AppRole.agent) ListTile(leading: const Icon(Icons.engineering), title: const Text('Assigned work'), onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => AgentScreen(state: state)))), const Divider(), ListTile(leading: const Icon(Icons.logout), title: const Text('Log out'), onTap: () => state.signOut())])); }

class AgentScreen extends StatelessWidget { const AgentScreen({super.key, required this.state}); final AppState state; @override Widget build(BuildContext context) => AppPage(title: 'Agent workspace', eyebrow: 'ASSIGNED WORK', child: Column(children: [...state.visibleRequests.where((r) => r.assignedAgent == state.actorId || r.assignedAgent != null).map((r) => Card(child: ListTile(title: Text(r.service.label), subtitle: Text('${r.id} · ${r.status.label}'), trailing: PopupMenuButton<RequestStatus>(onSelected: (status) => state.updateStatus(r, status), itemBuilder: (_) => lifecycle.map((s) => PopupMenuItem(value: s, child: Text(s.label))).toList()))))])); } }

class AdminScreen extends StatelessWidget { const AdminScreen({super.key, required this.state}); final AppState state; @override Widget build(BuildContext context) { final counts = {for (final status in RequestStatus.values) status: state.requests.where((r) => r.status == status).length}; return AppPage(title: 'Operations console', eyebrow: 'ADMIN PORTAL', child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Wrap(spacing: 8, runSpacing: 8, children: counts.entries.map((e) => SizedBox(width: 130, child: Card(child: Padding(padding: const EdgeInsets.all(14), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('${e.value}', style: const TextStyle(fontSize: 26, fontWeight: FontWeight.w800)), Text(e.key.label)]))))).toList()), const SizedBox(height: 18), const Text('Request management', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w800)), ...state.requests.map((r) => Card(child: ListTile(title: Text('${r.service.label} · ${r.id}'), subtitle: Text('${r.status.label} · ${r.address}'), trailing: PopupMenuButton<String>(onSelected: (value) { if (value.startsWith('assign:')) state.assignAgent(r, value.substring(7)); else state.updateStatus(r, RequestStatus.values.byName(value)); }, itemBuilder: (_) => [const PopupMenuItem(value: 'assign:Rohan Mehta', child: Text('Assign Rohan Mehta')), const PopupMenuItem(value: 'assign:Ankit Pawar', child: Text('Assign Ankit Pawar')), ...lifecycle.map((s) => PopupMenuItem(value: s.name, child: Text('Set ${s.label}')))]))), const SizedBox(height: 18), const Text('Audit activity', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w800)), ...state.auditLogs.take(20).map((log) => ListTile(dense: true, leading: const Icon(Icons.history), title: Text(log.eventType), subtitle: Text('${log.message} · ${log.actorId}')))])); } }

class AppPage extends StatelessWidget { const AppPage({super.key, required this.title, required this.eyebrow, required this.child}); final String title, eyebrow; final Widget child; @override Widget build(BuildContext context) => SafeArea(child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 920), child: Padding(padding: const EdgeInsets.fromLTRB(18, 20, 18, 28), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(eyebrow, style: TextStyle(fontSize: 10, letterSpacing: 1.1, color: Colors.grey.shade600, fontWeight: FontWeight.w700)), const SizedBox(height: 4), Text(title, style: const TextStyle(fontSize: 29, fontWeight: FontWeight.w800)), const SizedBox(height: 20), Expanded(child: SingleChildScrollView(child: child))])))); }

class HeroCard extends StatelessWidget { const HeroCard({super.key, required this.onTap}); final VoidCallback onTap; @override Widget build(BuildContext context) => Card(color: const Color(0xFFF26B4D), child: Padding(padding: const EdgeInsets.all(20), child: Row(children: [const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('HOME SERVICES, MADE EASY', style: TextStyle(color: Colors.white70, fontSize: 10, letterSpacing: 1)), SizedBox(height: 10), Text('Your to-do list\nstarts here.', style: TextStyle(color: Colors.white, fontSize: 26, fontWeight: FontWeight.w800)), SizedBox(height: 8), Text('Book trusted help in just a few taps.', style: TextStyle(color: Colors.white70))])), FilledButton(onPressed: onTap, style: FilledButton.styleFrom(backgroundColor: const Color(0xFF20233A)), child: const Text('Book a service'))]))); }

class ServiceTile extends StatelessWidget { const ServiceTile({super.key, required this.service, required this.onTap, this.large = false}); final ServiceType service; final VoidCallback onTap; final bool large; @override Widget build(BuildContext context) => SizedBox(width: large ? 180 : 120, child: Card(child: InkWell(onTap: onTap, borderRadius: BorderRadius.circular(14), child: Padding(padding: const EdgeInsets.all(14), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CircleAvatar(radius: 18, backgroundColor: const Color(0xFFFFE7DF), child: Icon(switch (service) { ServiceType.ac => Icons.ac_unit, ServiceType.plumbing => Icons.plumbing, ServiceType.electrical => Icons.bolt, ServiceType.cleaning => Icons.cleaning_services }, color: const Color(0xFFF26B4D), size: 18)), const SizedBox(height: 10), Text(service.label, style: const TextStyle(fontWeight: FontWeight.w800)), Text('From ₹${switch (service) { ServiceType.ac => '499', ServiceType.plumbing => '299', ServiceType.electrical => '249', ServiceType.cleaning => '599' }}', style: TextStyle(color: Colors.grey.shade600, fontSize: 11))])))); }

class RequestCard extends StatelessWidget { const RequestCard({super.key, required this.request, required this.onTap}); final ServiceRequest request; final VoidCallback onTap; @override Widget build(BuildContext context) => Card(child: InkWell(onTap: onTap, borderRadius: BorderRadius.circular(16), child: Padding(padding: const EdgeInsets.all(14), child: Row(children: [CircleAvatar(backgroundColor: const Color(0xFFECEBFF), child: Icon(Icons.home_repair_service, color: Colors.deepPurple.shade400)), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(request.service.label, style: const TextStyle(fontWeight: FontWeight.w800)), Text('${request.id} · ${request.status.label}', style: TextStyle(color: Colors.grey.shade600, fontSize: 11)), const SizedBox(height: 6), LinearProgressIndicator(value: request.status == RequestStatus.completed ? 1 : (lifecycle.indexOf(request.status) + 1) / lifecycle.length, color: const Color(0xFF1E9E96))])), const Icon(Icons.chevron_right)]))); }
